#pragma once

#include "gauge_interactions.hpp"

namespace wgphysics::research {

using PairTable = std::vector<std::size_t>;

inline std::size_t conjugated_pair(const AutomorphismTables& g,std::size_t x,uint16_t frame) {
    const auto n=g.order();
    const auto conjugate=[&](uint16_t a) {
        return g.multiply(frame,g.multiply(a,g.inverse(frame)));
    };
    return conjugate(x/n)*n+conjugate(x%n);
}

inline std::size_t reversed_pair(const AutomorphismTables& g,std::size_t x) {
    return g.inverse(x%g.order())*g.order()+g.inverse(x/g.order());
}

inline void validate_pair_table(const AutomorphismTables& g,const PairTable& table) {
    const auto n=g.order();
    if (table.size()!=static_cast<std::size_t>(n)*n)
        throw std::invalid_argument("pair table has wrong group size");
    auto sorted=table;
    std::sort(sorted.begin(),sorted.end());
    for (std::size_t x=0;x<table.size();++x)
        if (sorted[x]!=x) throw std::invalid_argument("pair table is not a bijection");
    const auto id=g.index_of(Permutation::identity(g.fiber_size()));
    if (table[id*n+id]!=static_cast<std::size_t>(id)*n+id)
        throw std::invalid_argument("pair rule does not fix flat vacuum");
    for (std::size_t x=0;x<table.size();++x) {
        const auto y=table[x];
        if (g.multiply(x/n,x%n)!=g.multiply(y/n,y%n))
            throw std::invalid_argument("pair table changes ordered product");
        if (table[reversed_pair(g,table[reversed_pair(g,x)])]!=x)
            throw std::invalid_argument("pair table violates orientation/time reversal");
        for (uint16_t frame=0;frame<n;++frame)
            if (table[conjugated_pair(g,x,frame)]!=conjugated_pair(g,y,frame))
                throw std::invalid_argument("pair table violates gauge equivariance");
    }
}

// Enumerate minimal involutions generated by one proposed x<->y exchange,
// closed under simultaneous gauge conjugation and J(A,B)=(B^-1,A^-1).
// This exhausts this construction, not all reversible equivariant laws.
inline std::vector<PairTable> search_pair_involutions(const AutomorphismTables& g) {
    const auto n=g.order();
    if (n>24) throw std::invalid_argument("bounded pair search supports groups of order <=24");
    const auto count=static_cast<std::size_t>(n)*n;
    std::set<PairTable> found;
    for (std::size_t x=0;x<count;++x) for (uint16_t a=0;a<n;++a) {
        const auto product=g.multiply(x/n,x%n);
        const auto b=g.multiply(g.inverse(a),product);
        const auto y=static_cast<std::size_t>(a)*n+b;
        PairTable table(count,count);
        std::vector<std::pair<std::size_t,std::size_t>> pending{{x,y},{y,x}};
        bool valid=true;
        for (std::size_t cursor=0;cursor<pending.size() && valid;++cursor) {
            const auto [from,to]=pending[cursor];
            if (table[from]!=count) { if (table[from]!=to) valid=false; continue; }
            table[from]=to;
            pending.emplace_back(to,from);
            pending.emplace_back(reversed_pair(g,from),reversed_pair(g,to));
            for (uint16_t frame=0;frame<n;++frame)
                pending.emplace_back(conjugated_pair(g,from,frame),conjugated_pair(g,to,frame));
        }
        if (!valid) continue;
        for (std::size_t i=0;i<count;++i) if (table[i]==count) table[i]=i;
        try { validate_pair_table(g,table); }
        catch (const std::invalid_argument&) { continue; }
        found.insert(std::move(table));
    }
    return {found.begin(),found.end()};
}

inline std::set<uint16_t> pair_generated_subgroup(const AutomorphismTables& g,std::size_t x) {
    const auto id=g.index_of(Permutation::identity(g.fiber_size()));
    std::set<uint16_t> result{id};
    std::vector<uint16_t> frontier{id};
    for (std::size_t i=0;i<frontier.size();++i)
        for (const uint16_t generator : {static_cast<uint16_t>(x/g.order()),static_cast<uint16_t>(x%g.order())}) {
            const auto next=g.multiply(frontier[i],generator);
            if (result.insert(next).second) frontier.push_back(next);
        }
    return result;
}

inline FiberBundleConnection apply_pair_table_interaction(
    const FiberBundleConnection& connection,const CellPairPatch& patch,const PairTable& table) {
    const AutomorphismTables group(connection.local_gauge_group());
    validate_pair_table(group,table);
    return realize_pair_interaction(connection,patch,[&](const auto& a,const auto& b) {
        const auto result=table[group.index_of(a)*group.order()+group.index_of(b)];
        return std::pair{group.elements()[result/group.order()],group.elements()[result%group.order()]};
    });
}

// Every equivariant involution decomposes into disjoint symmetry closures of
// its transpositions. Enumerate those disjoint unions without holding all tables.
// The explicit cap aborts rather than labelling a truncated search exhaustive.
template <typename Visitor>
inline std::size_t visit_pair_involutions(const AutomorphismTables& group,Visitor visitor,
                                         std::size_t maximum=2000000) {
    const auto atoms=search_pair_involutions(group);
    PairTable current(static_cast<std::size_t>(group.order())*group.order());
    std::iota(current.begin(),current.end(),0);
    std::vector<PairTable> supports;
    std::vector<PairTable> nontrivial;
    for (const auto& atom : atoms) {
        PairTable support;
        for (std::size_t x=0;x<atom.size();++x) if (atom[x]!=x) support.push_back(x);
        if (!support.empty()) { supports.push_back(support); nontrivial.push_back(atom); }
    }
    std::size_t count=0;
    const auto visit=[&](auto&& self,std::size_t first)->void {
        if (++count>maximum) throw std::runtime_error("pair-involution search hit explicit candidate cap");
        visitor(current);
        for (std::size_t i=first;i<nontrivial.size();++i) {
            bool disjoint=true;
            for (const auto x : supports[i]) if (current[x]!=x) { disjoint=false; break; }
            if (!disjoint) continue;
            for (const auto x : supports[i]) current[x]=nontrivial[i][x];
            self(self,i+1);
            for (const auto x : supports[i]) current[x]=x;
        }
    };
    visit(visit,0);
    return count;
}

} // namespace wgphysics::research
